//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLab.Kitchen.Capture.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ol-kitchen-document.documents.azure.com:443/")]
        public string EndPointUrl {
            get {
                return ((string)(this["EndPointUrl"]));
            }
            set {
                this["EndPointUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c3FCn0/d50L+YlDkIMWQJIaLvbcV5VNePlfjmGROj7c96UklxUGjHex80v+2IxTyJv34NKVpwx+VjUHLd" +
            "kHvFw==")]
        public string AuthorizationKey {
            get {
                return ((string)(this["AuthorizationKey"]));
            }
            set {
                this["AuthorizationKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OL-Kitchen-CaptureDB")]
        public string DatabaseId {
            get {
                return ((string)(this["DatabaseId"]));
            }
            set {
                this["DatabaseId"] = value;
            }
        }
    }
}
