//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLab.Kitchen.StorageRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KitchenStorageRepository : DbContext
    {
        public KitchenStorageRepository()
            : base("name=KitchenStorageRepository")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FieldDataType> FieldDataTypes { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<ThingData> ThingDatas { get; set; }
        public virtual DbSet<ThingDataFieldValue> ThingDataFieldValues { get; set; }
        public virtual DbSet<ThingDataType> ThingDataTypes { get; set; }
        public virtual DbSet<ThingFieldValue> ThingFieldValues { get; set; }
        public virtual DbSet<Thing> Things { get; set; }
        public virtual DbSet<ThingType> ThingTypes { get; set; }
    }
}
