//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLab.Kitchen.StorageRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThingFieldValue
    {
        public int Id { get; set; }
        public int ThingId { get; set; }
        public int FieldId { get; set; }
        public string Value { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Thing Thing { get; set; }
    }
}
