//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLab.Kitchen.StorageRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thing()
        {
            this.ThingData = new HashSet<ThingData>();
            this.ThingFieldValues = new HashSet<ThingFieldValue>();
        }
    
        public int Id { get; set; }
        public int LocationId { get; set; }
        public int ThingTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThingData> ThingData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThingFieldValue> ThingFieldValues { get; set; }
        public virtual ThingType ThingType { get; set; }
    }
}
